version: "3.8"

services:
  mongo_database:
    image: mongo:latest
    container_name: "mongo_database"
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "localdev"
      MONGO_INITDB_ROOT_PASSWORD: "localdev"
    volumes:
      - "./data:/data/db"

  web_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_service
    restart: always
    environment:
      NODE_ENV: "production"
    ports:
      - "3000:4600"
    links:
      - mongo_database
